---
# for docker
docker_registry_url: 192.168.1.201:1180

# for kubelet, kube-proxy
kube_master_url: http://192.168.1.201:1100
kube_pause_image_url: 192.168.1.201:1180/google_containers/pause

#!!!!!!!!! IMPORTANT - must be in kube-apiserver --service-cluster-ip-range RANGE !!!!!!!!
#cluster_dns_ip: 20.1.0.100
#cluster_domain_name: cluster.local

